apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: whisper-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo  # GCP standard persistent disk
  resources:
    requests:
      storage: 10Gi
