apiVersion: v1
kind: Service
metadata:
  name: whisper-service
  namespace: whisper-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: whisper-service
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer